version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/unnecessary-special-projects/ghist/cmd.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - name: ghist
    repository:
      owner: unnecessary-special-projects
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/unnecessary-special-projects/ghist"
    description: "Task management that lives in your repo."
    license: "MIT"
    install: |
      bin.install "ghist"
    test: |
      system "#{bin}/ghist", "--version"
